server:
  port: 8088
  forward-headers-strategy: framework

spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/noisemap_comments

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  use-fqn: true
  override-with-generic-response: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99
      slo:
        http:
          server:
            requests: 10ms,50ms,100ms,200ms,500ms,1s,2s
    tags:
      application: ${spring.application.name}