server:
  port: 8088
  forward-headers-strategy: framework

spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/noisemap_comments

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  use-fqn: true
  override-with-generic-response: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}