server:
  port: 8085

spring:
  application:
    name: gamification-service
  datasource:
    url: jdbc:postgresql://postgres:5432/noisemap_gamification
    username: ${DB_USERNAME:noisemap}
    password: ${DB_PASSWORD:noisemap}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
