server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: recording-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/noisemap_recordings
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

storage:
  audio:
    path: /data/audio

services:
  user-service:
    url: http://user-service:8081
  ml-service:
    url: ${ML_SERVICE_URL:http://ml-service:8000}
    timeout-seconds: 30

app:
  ml:
    default-dba-placeholder: 55.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  use-fqn: true
  override-with-generic-response: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99
      slo:
        http:
          server:
            requests: 10ms,50ms,100ms,200ms,500ms,1s,2s
    tags:
      application: ${spring.application.name}
