global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'api-gateway'

  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:8081']
        labels:
          application: 'user-service'

  - job_name: 'recording-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['recording-service:8082']
        labels:
          application: 'recording-service'

  - job_name: 'mapping-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['mapping-service:8083']
        labels:
          application: 'mapping-service'

  - job_name: 'statistics-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['statistics-service:8084']
        labels:
          application: 'statistics-service'

  - job_name: 'gamification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gamification-service:8085']
        labels:
          application: 'gamification-service'

  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8086']
        labels:
          application: 'notification-service'

  - job_name: 'moderation-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['moderation-service:8087']
        labels:
          application: 'moderation-service'

  - job_name: 'comment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['comment-service:8088']
        labels:
          application: 'comment-service'