server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: statistics-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/noisemap_statistics
    redis:
      host: redis
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

services:
  prediction:
    url: ${PREDICTION_SERVICE_URL:http://ml-prediction:5000}
    timeout-seconds: 10

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  use-fqn: true
  override-with-generic-response: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99
      slo:
        http:
          server:
            requests: 10ms,50ms,100ms,200ms,500ms,1s,2s
    tags:
      application: ${spring.application.name}