server:
  port: 8087
  forward-headers-strategy: framework

spring:
  application:
    name: moderation-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/noisemap_moderation
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  use-fqn: true
  override-with-generic-response: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99
      slo:
        http:
          server:
            requests: 10ms,50ms,100ms,200ms,500ms,1s,2s
    tags:
      application: ${spring.application.name}