server:
  port: 8087

spring:
  application:
    name: moderation-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/noisemap_moderation
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
